ORG 0x100          ; // PROGRAM STARTS AT MEMORY ADDRESS 0100H (.COM FILE FORMAT)

MOV DX, 0          ; // CLEAR DX (IMPORTANT FOR 16-BIT DIVISION — HIGH PART OF DIVIDEND)
MOV AX, 25         ; // AX = 25 (THIS IS THE DIVIDEND)
MOV BX, 5          ; // BX = 5 (THIS IS THE DIVISOR)
DIV BX             ; // DIVIDE AX BY BX → 25 / 5

MOV AX, 0x4C00     ; // EXIT PROGRAM
INT 0x21           ; // DOS SYSTEM CALL TO TERMINATE
