ORG 0X100   ;ORIGIN: PROGRAM STARTS AT MEMORY LOCATION 0100H (REQUIRED FOR .COM FILES)

MOV CX, 10  ;LOAD VALUE 10 INTO CX REGISTER (THIS WILL BE OUR LOOP COUNTER)
MOV AX, 0   ;INITIALIZE AX TO ZERO

L1:         ;LABEL L1 - START OF LOOP
ADD AX, 1   ;INCREMENT AX BY 1 IN EACH LOOP ITERATION
LOOP L1     ;DECREMENT CX, IF CX ≠ 0 THEN JUMP TO L1 AGAIN

MOV AX, 0X4C00  ;DOS FUNCTION TO EXIT PROGRAM (4C00H IN AX)
INT 0X21        ;CALL DOS INTERRUPT TO EXIT PROGRAM
